apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: php-html-vol1
  labels:
    name: data-pvc
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: log-vol2
  labels:
    name: logpvc
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi